export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LONGIN_ERROR = 'LOGIN_ERROR'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
